feat: add debug parameter for core
dashevo/dashmate pull request #349
Opened 2021-05-10 13:56 UTC by shuplenkov

## Issue being fixed or feature implemented

## What was done?

New `debug` parameter added to core
```./bin/mn config:set --config=local_seed core.debug true```

## How Has This Been Tested?

## Breaking Changes

No

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2021-05-11 13:30 UTC, shumkov commented on configs/schema/configJsonSchema.js
> +        debug: {
I would keep it boolean only and set the default value in the base config. Also, please update the migration.

2021-05-12 09:24 UTC, shumkov requested changes

2021-05-12 09:24 UTC, shumkov commented on configs/schema/configJsonSchema.js
>        required: ['docker', 'p2p', 'rpc', 'spork', 'masternode', 'miner', 'devnetName'],
`debug` must be here as well

2021-05-17 09:27 UTC, antouhou commented on configs/migrations.js
> +        if (typeof config.code.debug === 'undefined') {
core

2021-05-17 09:27 UTC, shumkov commented on configs/migrations.js
> +        if (typeof config.code.debug === 'undefined') {
`config.core.debug`

2021-05-17 10:09 UTC, shumkov approved these changes
LGTM! 👍

2021-05-17 10:11 UTC, shumkov commented on configs/migrations.js
> +        if (typeof config.core.debug === 'undefined') {
Since we merge it to 0.20 you need to add migration for the new version.

2021-05-17 10:12 UTC, shumkov requested changes

2021-05-17 10:12 UTC, shumkov commented on configs/migrations.js
> +        if (typeof config.core.debug === 'undefined') {
Since we merge it to 0.20 you need to add migration for the new version.

2021-05-19 09:53 UTC, shumkov submitted a review, later dismissed
👍

2021-05-19 09:54 UTC, shumkov approved these changes
👍

2021-05-19 09:57 UTC, merged